// filepath: c:\Projets\Personnel\Cyna_Projet\cyna-app\types\product.d.ts
export type Media = { url: string; [key: string]: any };
export type PricingModel = { label?: string; [key: string]: any };
export type Product = {
  id: number;
  priceId: string;
  name: string;
  brand: string;
  description: string;
  caracteristics: string;
  pricingModel: string | PricingModel;
  amount: number;
  categoryId: number;
  images?: Media[];
  status: string;
  createdAt: string;
  updatedAt: string;
  active: boolean;
  promo: boolean;
  salesNumber: number;
};

// Exemple à placer dans un fichier mock, ex: c:\Projets\Personnel\Cyna_Projet\cyna-app\types\mockProducts.ts

export const mockProducts: Product[] = [
  {
    id: 1,
    priceId: "price_001",
    name: "SentinelGuard",
    brand: "CyberSentinel",
    description:
      "Surveillance en temps réel des menaces réseau et alertes automatiques.",
    caracteristics:
      "Détection d'intrusion, alertes instantanées, rapports détaillés.",
    pricingModel: { label: "Mensuel" },
    amount: 9900,
    categoryId: 1,
    images: [
      {
        url: "https://www.bai.org/wp-content/uploads/2025/02/S.jpg",
      },
      {
        url: "https://www.bai.org/wp-content/uploads/2025/02/S.jpg",
      },
      {
        url: "https://www.bai.org/wp-content/uploads/2025/02/S.jpg",
      },
    ],
    status: "AVAILABLE",
    createdAt: "2024-01-10T09:00:00Z",
    updatedAt: "2024-05-01T10:00:00Z",
    active: true,
    promo: true,
    salesNumber: 120,
  },
  {
    id: 2,
    priceId: "price_002",
    name: "PhishBlocker",
    brand: "PhishSecure",
    description: "Protection avancée contre le phishing pour emails et web.",
    caracteristics: "Filtrage intelligent, analyse IA, rapports de tentatives.",
    pricingModel: { label: "Annuel" },
    amount: 19900,
    categoryId: 2,
    images: [{ url: "https://source.unsplash.com/featured/?cyber,security,2" }],
    status: "AVAILABLE",
    createdAt: "2024-02-15T09:00:00Z",
    updatedAt: "2024-05-01T10:00:00Z",
    active: true,
    promo: false,
    salesNumber: 80,
  },
  {
    id: 3,
    priceId: "price_003",
    name: "VulnScanner Pro",
    brand: "VulnTech",
    description: "Scan automatisé des vulnérabilités sur tous vos serveurs.",
    caracteristics: "Scan planifié, rapports PDF, API intégration.",
    pricingModel: { label: "Mensuel" },
    amount: 14900,
    categoryId: 3,
    images: [{ url: "https://source.unsplash.com/featured/?cyber,security,3" }],
    status: "AVAILABLE",
    createdAt: "2024-03-01T09:00:00Z",
    updatedAt: "2024-05-01T10:00:00Z",
    active: true,
    promo: false,
    salesNumber: 60,
  },
  {
    id: 4,
    priceId: "price_004",
    name: "DataEncryptor",
    brand: "SafeData",
    description:
      "Chiffrement automatique des données sensibles en transit et au repos.",
    caracteristics: "AES-256, gestion des clés, conformité RGPD.",
    pricingModel: { label: "Annuel" },
    amount: 24900,
    categoryId: 4,
    images: [{ url: "https://source.unsplash.com/featured/?cyber,security,4" }],
    status: "AVAILABLE",
    createdAt: "2024-01-20T09:00:00Z",
    updatedAt: "2024-05-01T10:00:00Z",
    active: true,
    promo: true,
    salesNumber: 95,
  },
  {
    id: 5,
    priceId: "price_005",
    name: "AccessManager",
    brand: "SecureAccess",
    description: "Gestion centralisée des accès et des identités (IAM).",
    caracteristics: "SSO, MFA, gestion des rôles.",
    pricingModel: { label: "Mensuel" },
    amount: 12900,
    categoryId: 5,
    images: [{ url: "https://source.unsplash.com/featured/?cyber,security,5" }],
    status: "AVAILABLE",
    createdAt: "2024-02-01T09:00:00Z",
    updatedAt: "2024-05-01T10:00:00Z",
    active: true,
    promo: false,
    salesNumber: 110,
  },
  {
    id: 6,
    priceId: "price_006",
    name: "LogMonitor",
    brand: "LogSecure",
    description: "Surveillance et analyse intelligente des logs systèmes.",
    caracteristics: "Alertes personnalisées, dashboard temps réel.",
    pricingModel: { label: "Mensuel" },
    amount: 8900,
    categoryId: 6,
    images: [{ url: "https://source.unsplash.com/featured/?cyber,security,6" }],
    status: "AVAILABLE",
    createdAt: "2024-03-10T09:00:00Z",
    updatedAt: "2024-05-01T10:00:00Z",
    active: true,
    promo: false,
    salesNumber: 70,
  },
  {
    id: 7,
    priceId: "price_007",
    name: "FirewallCloud",
    brand: "CloudDefender",
    description: "Pare-feu nouvelle génération pour cloud et SI hybrides.",
    caracteristics: "Règles dynamiques, protection DDoS.",
    pricingModel: { label: "Annuel" },
    amount: 29900,
    categoryId: 7,
    images: [{ url: "https://source.unsplash.com/featured/?cyber,security,7" }],
    status: "AVAILABLE",
    createdAt: "2024-01-25T09:00:00Z",
    updatedAt: "2024-05-01T10:00:00Z",
    active: true,
    promo: true,
    salesNumber: 130,
  },
  {
    id: 8,
    priceId: "price_008",
    name: "BackupSafe",
    brand: "DataGuard",
    description:
      "Sauvegarde automatique et restauration rapide des données critiques.",
    caracteristics: "Cloud sécurisé, restauration 1-clic.",
    pricingModel: { label: "Mensuel" },
    amount: 10900,
    categoryId: 8,
    images: [{ url: "https://source.unsplash.com/featured/?cyber,security,8" }],
    status: "AVAILABLE",
    createdAt: "2024-02-18T09:00:00Z",
    updatedAt: "2024-05-01T10:00:00Z",
    active: true,
    promo: false,
    salesNumber: 85,
  },
  {
    id: 9,
    priceId: "price_009",
    name: "PatchManager",
    brand: "UpdatePro",
    description:
      "Gestion automatisée des correctifs de sécurité sur tous vos systèmes.",
    caracteristics: "Planification, reporting, alertes de vulnérabilité.",
    pricingModel: { label: "Annuel" },
    amount: 17900,
    categoryId: 9,
    images: [{ url: "https://source.unsplash.com/featured/?cyber,security,9" }],
    status: "AVAILABLE",
    createdAt: "2024-03-05T09:00:00Z",
    updatedAt: "2024-05-01T10:00:00Z",
    active: true,
    promo: false,
    salesNumber: 77,
  },
  {
    id: 10,
    priceId: "price_010",
    name: "SIEM360",
    brand: "Cyber360",
    description:
      "Plateforme SIEM complète pour la détection et la réponse aux incidents.",
    caracteristics: "Corrélation d'événements, dashboards personnalisés.",
    pricingModel: { label: "Mensuel" },
    amount: 25900,
    categoryId: 10,
    images: [
      { url: "https://source.unsplash.com/featured/?cyber,security,10" },
    ],
    status: "AVAILABLE",
    createdAt: "2024-01-30T09:00:00Z",
    updatedAt: "2024-05-01T10:00:00Z",
    active: true,
    promo: true,
    salesNumber: 140,
  },
  {
    id: 11,
    priceId: "price_011",
    name: "MobileSecure",
    brand: "MobSafe",
    description: "Sécurité avancée pour flottes mobiles d'entreprise.",
    caracteristics: "MDM, chiffrement, détection de menaces mobiles.",
    pricingModel: { label: "Annuel" },
    amount: 13900,
    categoryId: 11,
    images: [
      { url: "https://source.unsplash.com/featured/?cyber,security,11" },
    ],
    status: "AVAILABLE",
    createdAt: "2024-02-22T09:00:00Z",
    updatedAt: "2024-05-01T10:00:00Z",
    active: true,
    promo: false,
    salesNumber: 65,
  },
  {
    id: 12,
    priceId: "price_012",
    name: "WebAppShield",
    brand: "AppDefender",
    description: "Protection des applications web contre les attaques OWASP.",
    caracteristics: "WAF, monitoring, alertes personnalisées.",
    pricingModel: { label: "Mensuel" },
    amount: 11900,
    categoryId: 12,
    images: [
      { url: "https://source.unsplash.com/featured/?cyber,security,12" },
    ],
    status: "AVAILABLE",
    createdAt: "2024-03-12T09:00:00Z",
    updatedAt: "2024-05-01T10:00:00Z",
    active: true,
    promo: false,
    salesNumber: 90,
  },
  {
    id: 13,
    priceId: "price_013",
    name: "DNSProtect",
    brand: "NetShield",
    description: "Protection DNS contre le spoofing et les attaques DDoS.",
    caracteristics: "Filtrage DNS, logs détaillés, alertes.",
    pricingModel: { label: "Annuel" },
    amount: 8900,
    categoryId: 13,
    images: [
      { url: "https://source.unsplash.com/featured/?cyber,security,13" },
    ],
    status: "AVAILABLE",
    createdAt: "2024-01-18T09:00:00Z",
    updatedAt: "2024-05-01T10:00:00Z",
    active: true,
    promo: true,
    salesNumber: 105,
  },
  {
    id: 14,
    priceId: "price_014",
    name: "UserAudit",
    brand: "AuditPlus",
    description:
      "Audit automatisé des comptes utilisateurs et détection d'anomalies.",
    caracteristics: "Rapports, alertes, conformité RGPD.",
    pricingModel: { label: "Mensuel" },
    amount: 9900,
    categoryId: 14,
    images: [
      { url: "https://source.unsplash.com/featured/?cyber,security,14" },
    ],
    status: "AVAILABLE",
    createdAt: "2024-02-10T09:00:00Z",
    updatedAt: "2024-05-01T10:00:00Z",
    active: true,
    promo: false,
    salesNumber: 55,
  },
  {
    id: 15,
    priceId: "price_015",
    name: "IncidentResponder",
    brand: "IRTech",
    description:
      "Gestion et automatisation de la réponse aux incidents de sécurité.",
    caracteristics: "Playbooks, alertes, intégration SIEM.",
    pricingModel: { label: "Annuel" },
    amount: 22900,
    categoryId: 15,
    images: [
      { url: "https://source.unsplash.com/featured/?cyber,security,15" },
    ],
    status: "AVAILABLE",
    createdAt: "2024-03-15T09:00:00Z",
    updatedAt: "2024-05-01T10:00:00Z",
    active: true,
    promo: false,
    salesNumber: 75,
  },
];
